package:
  name: python
  version: 2.7.13

source:
  fn: stackless-2713-export.tar.bz2
  url: http://www.stackless.com/binaries/stackless-2713-export.tar.bz2
  md5: c01210c08328f4afecb5d4c95d8af0ae
  patches:
    - version.patch
    - cprt.patch                      [False]
    - linux-clear_history.patch       [linux]
    - fix-readline-extra-space.patch  [linux and x86]
    - osx-dist.patch                  [osx and x86_64]
    - osx-site.patch                  [osx]
    - win-find_exe.patch              [win]
    - win-cygwin.patch                [win]
    - win-library_bin.patch           [win]
    - fd_setsize.patch                [win]

build:
  number: 0
  detect_binary_files_with_prefix: False
  no_link:
    - bin/python2.7                   [unix]
    - DLLs/_ctypes.pyd                [win]
  features:
    - debug                           [debug]
    - stackless
  track_features:
    - vc9                             [win]

requirements:
  build:
    - 7za                             [win]
    - curl                            [win]
    - bzip2                           [unix]
    - zlib 1.2.*                      [unix]
    - sqlite 3.13.*                   [unix]
    - readline 6.2                    [unix and x86]
    - tk 8.5.18                       [unix and x86]
    - openssl 1.0.2*                  [unix]
    - patch                           [win]
    - vc 9*                           [win]
  run:
    - zlib 1.2.*                      [unix]
    - sqlite 3.13.*                   [unix]
    - readline 6.2                    [unix and x86]
    - tk 8.5.18                       [unix and x86]
    - openssl 1.0.2*                  [unix]
    - vs2008_runtime                  [win]

test:
  commands:
    - python -V                       [unix]
    - pydoc -h
    - python-config --help            [unix]
    - idle -h                         [x86]
  files:
    - hello.txt.gz
  requires:
    - stackless

about:
  home: http://www.stackless.com/
  license: PSF
  license_file: LICENSE
  summary: general purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: http://stackless.readthedocs.io/en/v2.7.13-slp/
  dev_url: https://bitbucket.org/stackless-dev/stackless
